apiVersion: core.pingcap.com/v1alpha1
kind: PDGroup
metadata:
  name: pd
  labels:
    pingcap.com/group: pd
    pingcap.com/component: pd
    pingcap.com/cluster: sdb-datastore
spec:
  cluster:
    name: sdb-datastore
  replicas: 1
  template:
    spec:
      version: v8.5.8
      resources:
        cpu: 500m
        memory: 1Gi
      volumes:
      - name: data
        storage: 1Gi
        # storageClassName: premium-rwo
        mounts:
        - type: data
      config: |
{{- if .Values.encryption.enabled }}
        [security.encryption]
          data-encryption-method = "{{ .Values.encryption.dataEncryptionMethod }}"
          data-key-rotation-period = "{{ .Values.encryption.dataKeyRotationPeriod }}"
        [security.encryption.master-key]
          type = "kms"
          key-id = "{{ .Values.encryption.kms.keyID }}"
          vendor = "{{ .Values.encryption.kms.vendor }}"
{{- end }}
        [replication]
          location-labels = ["topology.kubernetes.io/zone", "kubernetes.io/hostname"]
          max-replicas = 3
      overlay:
        pod:
          spec:
            nodeSelector:
              dedicated: pd
{{- if .Values.encryption.enabled }}
            serviceAccountName: {{ .Values.serviceAccountName | quote }}
{{- end }}
              # # Recommended when running on GKE (non-Autopilot)
              # cloud.google.com/machine-family: n2
              # node.kubernetes.io/instance-type: n2-standard-4
            tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: pd
            topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
