apiVersion: core.pingcap.com/v1alpha1
kind: PDGroup
metadata:
  name: pd
  labels:
    pingcap.com/group: pd
    pingcap.com/component: pd
    pingcap.com/cluster: sdb-datastore
spec:
  cluster:
    name: sdb-datastore
  replicas: 1
  template:
    spec:
      version: v8.5.8
      resources:
        cpu: 500m
        memory: 1Gi
      volumes:
      - name: data
        storage: 1Gi
        storageClassName: premium-rwo
        mounts:
        - type: data
      config: |
        [replication]
          location-labels = ["topology.kubernetes.io/zone", "kubernetes.io/hostname"]
          max-replicas = 3
      {{- if .Values.tls.enabled }}
        [security]
          cert-allowed-cn = ["surrealdb", "cluster", "pd", "tikv"]
      {{- end }}
      overlay:
        pod:
          spec:
            # {{- if .Values.tls.enabled }}
            # volumes:
            # - name: pd-tls
            #   secret:
            #     secretName: pd-pd-cluster-secret
            # containers:
            # - name: pd
            #   volumeMounts:
            #   - name: pd-tls
            #     mountPath: /etc/pd-tls
            #     readOnly: true
            # {{- end }}
            # nodeSelector:
            #   dedicated: pd
            serviceAccountName: {{ .Values.serviceAccountName | quote }}
            # tolerations:
            # - effect: NoSchedule
            #   key: dedicated
            #   operator: Equal
            #   value: pd
            topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
