apiVersion: core.pingcap.com/v1alpha1
kind: TiKVGroup
metadata:
  name: tikv
  labels:
    pingcap.com/group: tikv
    pingcap.com/component: tikv
    pingcap.com/cluster: sdb-datastore
spec:
  cluster:
    name: sdb-datastore
  replicas: 1
  template:
    spec:
      version: v8.5.8
      resources:
        cpu: 500m
        memory: 3Gi
      volumes:
      - name: data
        storage: 1Gi
        # storageClassName: premium-rwo
        mounts:
        - type: data
      overlay:
        pod:
          spec:
            nodeSelector:
              dedicated: tikv
              # # Recommended when running on GKE (non-Autopilot)
              # cloud.google.com/machine-family: n2
              # node.kubernetes.io/instance-type: n2-standard-16
            tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: tikv
            topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
