apiVersion: core.pingcap.com/v1alpha1
kind: TiKVGroup
metadata:
  name: tikv
  labels:
    pingcap.com/group: tikv
    pingcap.com/component: tikv
    pingcap.com/cluster: sdb-datastore
spec:
  cluster:
    name: sdb-datastore
  replicas: 1
  template:
    spec:
      version: v8.5.8
      resources:
        cpu: 500m
        memory: 3Gi
      volumes:
      - name: data
        storage: 10Gi
        storageClassName: premium-rwo
        mounts:
        - type: data
      config: |
      {{- if .Values.tls.enabled }}
        [security]
          cert-allowed-cn = ["cluster", "pd", "tikv"]
      {{- end }}
      {{- if .Values.encryption.enabled }}
        [security.encryption]
          data-encryption-method = "{{ .Values.encryption.dataEncryptionMethod | default "aes256-ctr" }}"
          data-key-rotation-period = "{{ .Values.encryption.dataKeyRotationPeriod | default "168h" }}"
        [security.encryption.master-key]
          type = "kms"
          key-id = "{{ .Values.encryption.kms.keyID }}"
          region = "{{ .Values.encryption.kms.region }}"
          vendor = "{{ .Values.encryption.kms.vendor | default "gcp_v2" }}"
          gcp = {}
      {{- end }}
      overlay:
        pod:
          spec:
            # {{- if .Values.tls.enabled }}
            # volumes:
            # - name: tikv-tls
            #   secret:
            #     secretName: tikv-tikv-cluster-secret
            # containers:
            # - name: tikv
            #   volumeMounts:
            #   - name: tikv-tls
            #     mountPath: /etc/tikv-tls
            #     readOnly: true
            # {{- end }}
            terminationGracePeriodSeconds: 600
            # nodeSelector:
            #   dedicated: tikv
            serviceAccountName: {{ .Values.serviceAccountName | quote }}
            # tolerations:
            # - effect: NoSchedule
            #   key: dedicated
            #   operator: Equal
            #   value: tikv
            topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
