apiVersion: core.pingcap.com/v1alpha1
kind: TiKVGroup
metadata:
  name: tikv
  labels:
    pingcap.com/group: tikv
    pingcap.com/component: tikv
    pingcap.com/cluster: sdb-datastore
spec:
  cluster:
    name: sdb-datastore
  replicas: {{ .Values.replicas }}
  template:
    spec:
      version: {{ .Values.version }}
      resources:
        cpu: {{ .Values.resources.cpu }}
        memory: {{ .Values.resources.memory }}
      volumes:
      - name: data
        storage: {{ .Values.volumes.data.storage }}
        storageClassName: {{ .Values.volumes.data.storageClassName }}
        mounts:
        - type: data
      config: |
      {{- if .Values.tls.enabled }}
        [security]
          cert-allowed-cn = ["cluster", "pd", "tikv"]
      {{- end }}
      {{- if .Values.encryption.enabled }}
        [security.encryption]
          data-encryption-method = "{{ .Values.encryption.dataEncryptionMethod | default "aes256-ctr" }}"
          data-key-rotation-period = "{{ .Values.encryption.dataKeyRotationPeriod | default "168h" }}"
        [security.encryption.master-key]
          type = "kms"
          key-id = "{{ .Values.encryption.kms.keyID }}"
          region = "{{ .Values.encryption.kms.region }}"
          vendor = "{{ .Values.encryption.kms.vendor | default "gcp_v2" }}"
          gcp = {}
      {{- end }}
      overlay:
        pod:
          spec:
            terminationGracePeriodSeconds: 600
            # nodeSelector:
            #   dedicated: tikv
            serviceAccountName: {{ .Values.serviceAccountName | quote }}
            # tolerations:
            # - effect: NoSchedule
            #   key: dedicated
            #   operator: Equal
            #   value: tikv
            topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
