apiVersion: core.pingcap.com/v1alpha1
kind: PDGroup
metadata:
  name: pd
  labels:
    pingcap.com/group: pd
    pingcap.com/component: pd
    pingcap.com/cluster: sdb-datastore
spec:
  cluster:
    name: sdb-datastore
  replicas: {{ .Values.replicas }}
  template:
    spec:
      version: {{ .Values.version }}
      resources:
        cpu: {{ .Values.resources.cpu }}
        memory: {{ .Values.resources.memory }}
      volumes:
      - name: data
        storage: {{ .Values.volumes.data.storage }}
        storageClassName: {{ .Values.volumes.data.storageClassName }}
        mounts:
        - type: data
      config: |
        [replication]
          location-labels = ["topology.kubernetes.io/zone", "kubernetes.io/hostname"]
          max-replicas = {{ .Values.maxReplicas | default 3 }} # Copies of each data piece across different zones
      {{- if .Values.tls.enabled }}
        [security]
          cert-allowed-cn = ["surrealdb", "cluster", "pd", "tikv"]
      {{- end }}
      overlay:
        pod:
          spec:
            # nodeSelector:
            #   dedicated: pd
            serviceAccountName: {{ .Values.serviceAccountName | quote }}
            # tolerations:
            # - effect: NoSchedule
            #   key: dedicated
            #   operator: Equal
            #   value: pd
            topologySpreadConstraints:
            - topologyKey: topology.kubernetes.io/zone
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
