{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
{{- if .Values.monitoring.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoring.serviceAccount.name }}
  annotations:
{{- toYaml .Values.monitoring.serviceAccount.annotations | nindent 4 }}
{{- end }}
