# Values for my local kind deployment
replicaCount: 1

image:
  repository: surrealdb/surrealdb
  pullPolicy: IfNotPresent
  tag: v3.2.3

imagePullSecrets: []

nameOverride: "surrealdb"
fullnameOverride: ""

args: [start]

surrealdb:
  path: tikv://pd-pd:2379
  log: info
  auth: true
  initial_user: "root"
  initial_pass: "root"
  port: 8000

strategy:
  type: RollingUpdate

serviceAccount:
  create: false

podExtraEnv: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
initContainers: []
extraContainers: []

service:
  type: NodePort
  port: 8000
  selector:
    app: surrealdb

ingress:
  enabled: false

# resources:
#   requests:
#     cpu: 500m
#     memory: 1Gi

lifecycle: {}
terminationGracePeriodSeconds: null

horizontalPodAutoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  metrics: []

nodeSelector: {}
tolerations: []
affinity: {}
volumes: []
volumeMounts: []

persistence:
  enabled: false

livenessProbe:
  httpGet:
    path: /health
    port: http
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /ready
    port: http
  timeoutSeconds: 5
