encryption:
  enabled: true
  dataEncryptionMethod: aes256-ctr
  dataKeyRotationPeriod: 168h
  kms:
    keyID: ""
    region: ""

# Format: gke-tikv-<cluster_key>
serviceAccountName: gke-tikv-<REGION>-1
